version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: raul_silva_postgres_objetivo3
    restart: unless-stopped

    environment:
      POSTGRES_USER: raul_silva_user
      POSTGRES_PASSWORD: raul_silva_pass
      POSTGRES_DB: raul_silva_db

    volumes:
      # PostgreSQL ejecuta los .sql en orden alfab√©tico
      - ./scripts:/docker-entrypoint-initdb.d:ro

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U raul_silva_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_objetivo3:
    name: raul_silva_postgres_data_objetivo3
